# This file was generated by GoReleaser. DO NOT EDIT.
cask "ocfl-tools" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "ddb5f1589032fffcfaa65ecb5e78691e7d7c10e572f07263c0e3e8301e7dda99"
      url "https://github.com/srerickson/ocfl-tools/releases/download/v#{version}/ocfl-tools_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4a99880c9d6801d98ac5d7d68d8a3a2250d33ac84f6cb837696b555ff9bbebc6"
      url "https://github.com/srerickson/ocfl-tools/releases/download/v#{version}/ocfl-tools_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4399964bf4490ccbf87efd683df23cf8c84975e9cb99318c4708853ca755f860"
      url "https://github.com/srerickson/ocfl-tools/releases/download/v#{version}/ocfl-tools_Linux_arm64.tar.gz"
    end
  end

  name "ocfl-tools"
  desc "Command-line tools for working with OCFL repositories"
  homepage "https://github.com/srerickson/ocfl-tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ocfl"

  # No zap stanza required

end
