# This file was generated by GoReleaser. DO NOT EDIT.
cask "ocfl-tools" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "c1481037a9adb3c27a7a09c552334a6e2c24941e7f47fe32cdce624aee6cfd9f"
      url "https://github.com/srerickson/ocfl-tools/releases/download/v#{version}/ocfl-tools_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f812b345a16fa3cc5a3ee536d6b5cdebae51c40a62b7d4385aa05bdc9dc0a429"
      url "https://github.com/srerickson/ocfl-tools/releases/download/v#{version}/ocfl-tools_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ee9cd3c79af2486dd4893d6b981cd87f1b61fb5dc68beda9491cc0d75c82b112"
      url "https://github.com/srerickson/ocfl-tools/releases/download/v#{version}/ocfl-tools_Linux_arm64.tar.gz"
    end
  end

  name "ocfl-tools"
  desc "Command-line tools for working with OCFL repositories"
  homepage "https://github.com/srerickson/ocfl-tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ocfl"

  # No zap stanza required

end
